[workspace]
members = [
    "e2ee"
]
default-members = [
    "e2ee"
]
resolver = "2"

[workspace.dependencies]
aws-lc-rs = "1.13"
once_cell = { version = "1", features = ["alloc", "race"], default-features = false }
zeroize = "1.8"
hex = "0.4"
