[workspace]
members = [
    "e2ee"
, "e2ee-provider"]
default-members = [
    "e2ee"
]
resolver = "2"

[workspace.dependencies]
aws-lc-rs = "1.14"
openssl = "0.10"
once_cell = { version = "1", features = ["alloc", "race"], default-features = false }
zeroize = "1.8"
hex = "0.4"
paste = "1"
