[workspace]
members = [
    "e2ee"
]
default-members = [
    "e2ee"
]
resolver = "2"

[workspace.dependencies]
ring = "0.17"
once_cell = { version = "1", features = ["alloc", "race"], default-features = false }
